### PR TITLE
Issue 168, add venue scrolling feature

### PR DESCRIPTION
**Pull request by sweetstyle11**

### CODE REVIEW

**Comment by sweetstyle11** [comment]
I'm trying to implement a 'side scrolling' feature that scrolls through the calendar of venues and events  when either the left or right arrow is clicked. Can someone please maybe point me in a right direction or give me a technique to google. My first thought was to hide/ unhide rows depending on which is clicked, but I came across a technique where I can scroll by a set number of pixels in javascript using: window.scrollBy(x, y) paired with an event listener. Would either of these be a valid approach? I can also foresee potential problems with either one of these approaches as the screen size increases and more calendar rows are shown.

**Comment by sumeetjain** [comment]
I think either approach would be valid. I can't foresee any issues, but it's hard to see that far ahead for features like this.

> I can also foresee potential problems with either one of these approaches as the screen size increases and more calendar rows are shown.

This is true. To deal with it, you might find that the [`resize`](https://developer.mozilla.org/en-US/docs/Web/Events/resize) event helps you programmatically alter your `x` and `y` (and other) values when the browser size is altered.

Or, if you're not trying to accommodate the action of resizing itself but rather just different screensizes... Then you can check the `window` or `document` elements on pageload to see what kind of measurements are needed.

**Comment by sweetstyle11** [comment]
Real quick, I have text inside of a div that's floated left and has a set width. For some reason I can't get that text to wrap. I've tried: 
 white-space: pre-wrap; 
    overflow-wrap: break-word; 
    word-wrap: normal;
    word-break: break-all;
And nothing is happening. The text is being hidden, like if it has an overflow: hidden on it. But it doesn't.

**Comment by sweetstyle11** [comment]
To be specific the text is in a class like this: 
         <div class="show show--60 show--21-plus">
            Joy Division
          </div>

**Comment by sweetstyle11** [comment]
`<div class="show show--60 show--21-plus">
            Joy Division
          </div>
`

**Pull request merged**
